### ISSUE TITLE
=dev-java/jython-2.7.0-r2 fails with Python AttributeError

### ISSUE THREAD

**Issue by TheChymera** [gentoo/sci#1048]
@mmokrejs it seems you're the only contributor to have had anything to do with this package. Any ideas what's going on with it, and whether we can fix or just drop it?

https://ppb.chymera.eu/716f84.log

This being the issue:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/tmp/portage/dev-java/jython-2.7.0-r2/image/usr/share/jython-2.7/Lib/distutils/sysconfig.py", line 28, in <module>
    project_base = os.path.dirname(os.path.realpath(sys.executable))
  File "/var/tmp/portage/dev-java/jython-2.7.0-r2/image/usr/share/jython-2.7/Lib/posixpath.py", line 367, in realpath
    path, ok = _joinrealpath('', filename, {})
  File "/var/tmp/portage/dev-java/jython-2.7.0-r2/image/usr/share/jython-2.7/Lib/posixpath.py", line 373, in _joinrealpath
    if isabs(rest):
  File "/var/tmp/portage/dev-java/jython-2.7.0-r2/image/usr/share/jython-2.7/Lib/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

To me it looks like some of the internal python installation code is getting none when expecting some sort of path. Perhaps related to python version, but no idea really...

**Comment by AndrewAmmerlaan** [comment]
Closing because package is not in ::science anymore
