### ISSUE TITLE
sci-libs/mlpack-3.4.2  ERROR: No matching distribution found for pytest-runner

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [gentoo/sci#1086]
```
[73/728] cd /var/tmp/portage/sci-libs/mlpack-3.4.2/work/mlpack-3.4.2_build/src/mlpack/bindings/python && /usr/bin/cmake -E env NO_BUILD=1 /var/tmp/portage/sci-libs/mlpack-3.4.2/temp/python3.8/bin/python /var/tmp/portage/sci-libs/mlpack-3.4.2/work/mlpack-3.4.2_build/src/mlpack/bindings/python/setup.py build
FAILED: src/mlpack/bindings/python/CMakeFiles/python_configured.util 
cd /var/tmp/portage/sci-libs/mlpack-3.4.2/work/mlpack-3.4.2_build/src/mlpack/bindings/python && /usr/bin/cmake -E env NO_BUILD=1 /var/tmp/portage/sci-libs/mlpack-3.4.2/temp/python3.8/bin/python /var/tmp/portage/sci-libs/mlpack-3.4.2/work/mlpack-3.4.2_build/src/mlpack/bindings/python/setup.py build
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7534847bb730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7534847b0b20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7534847bb760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7534847bb910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7534847bbac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pytest-runner/
ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
ERROR: No matching distribution found for pytest-runner
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/portage/sci-libs/mlpack-3.4.2/temp/tmpmaef5i66', '--quiet', 'pytest-runner']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/tmp/portage/sci-libs/mlpack-3.4.2/work/mlpack-3.4.2_build/src/mlpack/bindings/python/setup.py", line 108, in <module>
    setup(name='mlpack',
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 779, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 838, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/lib/python3.8/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/tmp/portage/sci-libs/mlpack-3.4.2/temp/tmpmaef5i66', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
```

**Comment by Alessandro-Barbieri** [comment]
@epsilon-0 have you seen this?

**Comment by epsilon-0** [comment]
Ah, I hadn't seen this.
Will check it out.

**Comment by Alessandro-Barbieri** [comment]
Can you also checkout #1084 and #1085?
