### ISSUE TITLE
suggestion for new ebuild: sci-electronics/wattwaechter-bin

### ISSUE THREAD

**Issue by jonasstein** [gentoo/sci#253]
EMF monitoring by the Federal Network Agency for ham radio operators. 
Wattwaechter calculates antenna characteristics. It is written in java.

http://emf3.bundesnetzagentur.de/en_emf_mon.html
http://emf3.bundesnetzagentur.de/wattw%C3%A4chter.html

**Comment by marbre** [comment]
Well I could write an ebuild, but the jar doesn't runs on my machine:

>marbre@... ~/Downloads/tmp $ java -jar wattwaechter_cb_2014_02_12.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/pktec/wasa/gui/WasaApp : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)


>marbre@... ~/Downloads/tmp $ java -version
java version "1.6.0_33"
OpenJDK Runtime Environment (IcedTea6 1.13.5) (Gentoo package icedtea-6.1.13.5-r1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)


Did you got it running? Furthermore, we need to know the license under which the software is released.
